Write([[<!DOCTYPE>]])
Write([[<head>]])
Write([[<title>starlight</title>]])
Write([[<script src="/js/framework.js">]])
Write([[</script>]])
Write([[</head>]])
Write([[<body>]])
Write([[<h1>hi there</h1>]])
Write([[</body>]])
